server {
  listen 80;
  server_name _;

  root /var/www/frontend;
  index index.html;

  # React SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Proxy API calls to INTERNAL ALB
  location /api/ {
    proxy_pass http://internal-ALBAPP-1334638460.us-east-2.elb.amazonaws.com/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
